// Generated by CoffeeScript 1.8.0
(function() {
  var fs, ribcage, util, _;

  ribcage = require('ribcage');

  util = require('util');

  fs = require('fs');

  _ = require('underscore');

  ribcage.init({}, function(err, env) {
    return _.each(env.settings.rules.forward, function(rule) {
      var compiled;
      compiled = ['iptables -A FORWARD'];
      if (rule.proto) {
        compiled.push("-p " + rule.proto);
      } else {
        compiled.push("-p tcp");
      }
      if (rule.from.indexOf('-') === -1) {
        compiled.push("-s " + rule.from);
      } else {
        compiled.push("-m iprange --src-range " + rule.from);
      }
      if (!rule.port) {
        throw "no port " + rule;
      }
      if (rule.port.constructor === Number || rule.port.indexOf('-') === -1) {
        compiled.push("--dport " + rule.port);
      } else {
        compiled.push("--match multiport --dports " + rule.port);
      }
      compiled.push("-m state --state NEW,ESTABLISHED,RELATED -j ACCEPT");
      return console.log(compiled.join(' '));
    });
  });

}).call(this);
