// Generated by CoffeeScript 1.8.0
(function() {
  var fs, ribcage, util, _;

  ribcage = require('ribcage');

  util = require('util');

  fs = require('fs');

  _ = require('underscore');

  ribcage.init({}, function(err, env) {
    var hosts, pings, rules;
    rules = env.settings.rules;
    if (!rules.forward) {
      rules.forward = [];
    }
    hosts = env.settings.hosts;
    _.map(hosts, function(host, hostName) {
      if (host.ports) {
        return _.map(host.ports, function(port, portName) {
          var rule;
          rule = _.extend({}, _.pick(port, 'proto', 'port'));
          rule.to = host.ip;
          rule.from = port.from;
          rule.comment = "" + port.from + " --> " + hostName + ":" + portName;
          rule._toName = hostName;
          rule._fromName = port.from;
          return rules.forward.push(rule);
        });
      }
    });
    _.each(rules.forward, function(rule) {
      var compiled;
      compiled = ['iptables -A FORWARD'];
      if (rule.proto) {
        compiled.push("-p " + rule.proto);
      } else {
        compiled.push("-p tcp");
      }
      if (hosts[rule.from]) {
        rule.from = hosts[rule.from].ip;
      }
      if (hosts[rule.to]) {
        rule.to = hosts[rule.to].ip;
      }
      if (rule.from.indexOf('-') === -1) {
        compiled.push("-s " + rule.from);
      } else {
        compiled.push("-m iprange --src-range " + rule.from);
      }
      if (rule.port) {
        if (rule.port.constructor === Number || rule.port.indexOf('-') === -1) {
          compiled.push("--dport " + rule.port);
        } else {
          compiled.push("--match multiport --dports " + rule.port);
        }
      }
      compiled.push("-m state --state NEW,ESTABLISHED,RELATED -j ACCEPT");
      if (rule.comment) {
        console.log("# " + rule.comment);
      }
      return console.log(compiled.join(' '));
    });
    pings = [];
    _.each(env.settings.rules.forward, function(rule) {
      if (!_.find(pings, function(entry) {
        return entry.from === rule.from && entry.to === rule.to;
      })) {
        return pings.push({
          from: rule.from,
          to: rule.to,
          comment: "" + rule._fromName + " -- ping -> " + rule._toName
        });
      }
    });
    console.log("\n# ping definitions\n");
    return _.each(pings, function(rule) {
      var compiled;
      compiled = ['iptables -A FORWARD'];
      if (rule.from.indexOf('-') === -1) {
        compiled.push("-s " + rule.from);
      } else {
        compiled.push("-m iprange --src-range " + rule.from);
      }
      if (rule.to.indexOf('-') === -1) {
        compiled.push("-d " + rule.to);
      } else {
        compiled.push("-m iprange --dst-range " + rule.to);
      }
      compiled.push('-p icmp --icmp-type echo-request -j ACCEPT');
      if (rule.comment) {
        console.log("# " + rule.comment);
      }
      return console.log(compiled.join(' '));
    });
  });

}).call(this);
